### ISSUE TITLE
Site rendered poorly on IE 11

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/www.isotc211.org#24]
From @MatsAhlin :
> It seems also be a problem for all people in governmental positions that are restricted in using the Microsoft Explorer (yes still) that experience problem with the page. Text being placed on top of other text and so on.

* Microsoft Edge (the browser on Windows 10) works fine
* IE 11 has issues (see below)

![image](https://user-images.githubusercontent.com/11865/57770872-dca7a800-7743-11e9-8164-86c002769b30.png)

**Comment by strogonoff** [comment]
Addressed in theme version 0.4.4, verified in IE down to 9.

**Comment by ronaldtse** [comment]
@strogonoff I'm still seeing this on IE 11... has it been deployed?

<img width="618" alt="Screen Shot 2019-05-16 at 9 55 48 AM" src="https://user-images.githubusercontent.com/11865/57820808-c986ed80-77c0-11e9-85cf-9cd8704d37ad.png">

**Comment by strogonoff** [comment]
Thanks! Indeed, fix was not applied thoroughly, production looks OK in IE 11 now @ronaldtse

**Comment by ronaldtse** [comment]
This should be fixed now (see screenshot). @MatsAhlin can you help confirm? Thanks!

<img width="880" alt="Screen Shot 2019-05-17 at 1 21 53 PM" src="https://user-images.githubusercontent.com/11865/57904788-d5e57600-78a6-11e9-97cb-437f6f451e70.png">

**Comment by MatsAhlin** [comment]
I can confirm it now working much better.
Thanks Ron
Thanks Anton

**Comment by ronaldtse** [comment]
That's awesome -- thanks @MatsAhlin for reporting and confirming the fix!
